### ISSUE TITLE
Pad op is not supported

### ISSUE THREAD

**Issue by souptc** [onnx/onnx-coreml#10]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cheng/anaconda3/envs/py27/lib/python2.7/site-packages/onnx_coreml/_onnx_converter.py", line 219, in convert
    _convert_node(builder, node)
  File "/home/cheng/anaconda3/envs/py27/lib/python2.7/site-packages/onnx_coreml/_layers.py", line 390, in _convert_node
    converter_fn = _get_node_converter_fn(node)
  File "/home/cheng/anaconda3/envs/py27/lib/python2.7/site-packages/onnx_coreml/_layers.py", line 385, in _get_node_converter_fn
    "ONNX node of type {} is not supported.".format(op_type,)
TypeError: ONNX node of type Pad is not supported.

Could we add "pad" support? pad is a very common op.

**Comment by aseemw** [comment]
This op should be in the master now. 
Can you check again by installing from the source as described in the readme file? The PyPI package is out of date.
