### ISSUE TITLE
Unsupported ONNX ops of type: Gather,Tile

### ISSUE THREAD

**Issue by UdonDa** [onnx/onnx-coreml#344]
I was able to convert the model that created this source(https://github.com/yunjey/StarGAN) code to onnx.

However, an error occurred during conversion from onnx to coreml.
This is the error code.
```
Traceback (most recent call last):
  File "onnx2coreml.py", line 13, in <module>
    mlmodel = convert(model_in)
  File "hoge/lib/python3.6/site-packages/onnx_coreml/converter.py", line 449, in convert
    _check_unsupported_ops(graph.nodes)
  File "hoge/lib/python3.6/site-packages/onnx_coreml/converter.py", line 140, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported ONNX ops of type: Gather,Tile
```

This is the source code.
```
import onnx

model_in = "Generetaor.onnx"
model_out = "Generator.mlmodel"

model = onnx.load(model_in)
print(onnx.helper.printable_graph(model.graph))
mlmodel = convert(model_in)
```

This is the model.graph
>print(onnx.helper.printable_graph(model.graph))
```
graph torch-jit-export (
  %0[FLOAT, 16x3x256x256]
  %1[FLOAT, 16x10]
) initializers (
  %2[FLOAT, 64x13x7x7]
  %3[FLOAT, 64]
  %4[FLOAT, 64]
  %5[FLOAT, 64]
  %6[FLOAT, 64]
  %7[INT64, scalar]
  %8[FLOAT, 128x64x4x4]
  %9[FLOAT, 128]
  %10[FLOAT, 128]
  %11[FLOAT, 128]
  %12[FLOAT, 128]
  %13[INT64, scalar]
  %14[FLOAT, 256x128x4x4]
  %15[FLOAT, 256]
  %16[FLOAT, 256]
  %17[FLOAT, 256]
  %18[FLOAT, 256]
  %19[INT64, scalar]
  %20[FLOAT, 256x256x3x3]
  %21[FLOAT, 256]
  %22[FLOAT, 256]
  %23[FLOAT, 256]
  %24[FLOAT, 256]
  %25[INT64, scalar]
  %26[FLOAT, 256x256x3x3]
  %27[FLOAT, 256]
  %28[FLOAT, 256]
  %29[FLOAT, 256]
  %30[FLOAT, 256]
  %31[INT64, scalar]
  %32[FLOAT, 256x256x3x3]
  %33[FLOAT, 256]
  %34[FLOAT, 256]
  %35[FLOAT, 256]
  %36[FLOAT, 256]
  %37[INT64, scalar]
  %38[FLOAT, 256x256x3x3]
  %39[FLOAT, 256]
  %40[FLOAT, 256]
  %41[FLOAT, 256]
  %42[FLOAT, 256]
  %43[INT64, scalar]
  %44[FLOAT, 256x256x3x3]
  %45[FLOAT, 256]
  %46[FLOAT, 256]
  %47[FLOAT, 256]
  %48[FLOAT, 256]
  %49[INT64, scalar]
  %50[FLOAT, 256x256x3x3]
  %51[FLOAT, 256]
  %52[FLOAT, 256]
  %53[FLOAT, 256]
  %54[FLOAT, 256]
  %55[INT64, scalar]
  %56[FLOAT, 256x256x3x3]
  %57[FLOAT, 256]
  %58[FLOAT, 256]
  %59[FLOAT, 256]
  %60[FLOAT, 256]
  %61[INT64, scalar]
  %62[FLOAT, 256x256x3x3]
  %63[FLOAT, 256]
  %64[FLOAT, 256]
  %65[FLOAT, 256]
  %66[FLOAT, 256]
  %67[INT64, scalar]
  %68[FLOAT, 256x256x3x3]
  %69[FLOAT, 256]
  %70[FLOAT, 256]
  %71[FLOAT, 256]
  %72[FLOAT, 256]
  %73[INT64, scalar]
  %74[FLOAT, 256x256x3x3]
  %75[FLOAT, 256]
  %76[FLOAT, 256]
  %77[FLOAT, 256]
  %78[FLOAT, 256]
  %79[INT64, scalar]
  %80[FLOAT, 256x256x3x3]
  %81[FLOAT, 256]
  %82[FLOAT, 256]
  %83[FLOAT, 256]
  %84[FLOAT, 256]
  %85[INT64, scalar]
  %86[FLOAT, 256x256x3x3]
  %87[FLOAT, 256]
  %88[FLOAT, 256]
  %89[FLOAT, 256]
  %90[FLOAT, 256]
  %91[INT64, scalar]
  %92[FLOAT, 256x128x4x4]
  %93[FLOAT, 128]
  %94[FLOAT, 128]
  %95[FLOAT, 128]
  %96[FLOAT, 128]
  %97[INT64, scalar]
  %98[FLOAT, 128x64x4x4]
  %99[FLOAT, 64]
  %100[FLOAT, 64]
  %101[FLOAT, 64]
  %102[FLOAT, 64]
  %103[INT64, scalar]
  %104[FLOAT, 3x64x7x7]
) {
  %105 = Constant[value = <Scalar Tensor []>]()
  %106 = Shape(%1)
  %107 = Gather[axis = 0](%106, %105)
  %108 = Constant[value = <Scalar Tensor []>]()
  %109 = Shape(%1)
  %110 = Gather[axis = 0](%109, %108)
  %111 = Constant[value = <Scalar Tensor []>]()
  %112 = Constant[value = <Scalar Tensor []>]()
  %113 = Unsqueeze[axes = [0]](%107)
  %114 = Unsqueeze[axes = [0]](%110)
  %115 = Unsqueeze[axes = [0]](%111)
  %116 = Unsqueeze[axes = [0]](%112)
  %117 = Concat[axis = 0](%113, %114, %115, %116)
  %118 = Reshape(%1, %117)
  %119 = Constant[value = <Scalar Tensor []>]()
  %120 = Shape(%0)
  %121 = Gather[axis = 0](%120, %119)
  %122 = Constant[value = <Scalar Tensor []>]()
  %123 = Shape(%0)
  %124 = Gather[axis = 0](%123, %122)
  %125 = Constant[value = <Scalar Tensor []>]()
  %126 = Constant[value = <Scalar Tensor []>]()
  %127 = Unsqueeze[axes = [0]](%125)
  %128 = Unsqueeze[axes = [0]](%126)
  %129 = Unsqueeze[axes = [0]](%121)
  %130 = Unsqueeze[axes = [0]](%124)
  %131 = Concat[axis = 0](%127, %128, %129, %130)
  %132 = Tile(%118, %131)
  %133 = Concat[axis = 1](%0, %132)
  %134 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [1, 1]](%133, %2)
  %135 = InstanceNormalization[epsilon = 9.99999974737875e-06](%134, %3, %4)
  %136 = Relu(%135)
  %137 = Conv[dilations = [1, 1], group = 1, kernel_shape = [4, 4], pads = [1, 1, 1, 1], strides = [2, 2]](%136, %8)
  %138 = InstanceNormalization[epsilon = 9.99999974737875e-06](%137, %9, %10)
  %139 = Relu(%138)
  %140 = Conv[dilations = [1, 1], group = 1, kernel_shape = [4, 4], pads = [1, 1, 1, 1], strides = [2, 2]](%139, %14)
  %141 = InstanceNormalization[epsilon = 9.99999974737875e-06](%140, %15, %16)
  %142 = Relu(%141)
  %143 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%142, %20)
  %144 = InstanceNormalization[epsilon = 9.99999974737875e-06](%143, %21, %22)
  %145 = Relu(%144)
  %146 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%145, %26)
  %147 = InstanceNormalization[epsilon = 9.99999974737875e-06](%146, %27, %28)
  %148 = Add(%142, %147)
  %149 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%148, %32)
  %150 = InstanceNormalization[epsilon = 9.99999974737875e-06](%149, %33, %34)
  %151 = Relu(%150)
  %152 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%151, %38)
  %153 = InstanceNormalization[epsilon = 9.99999974737875e-06](%152, %39, %40)
  %154 = Add(%148, %153)
  %155 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%154, %44)
  %156 = InstanceNormalization[epsilon = 9.99999974737875e-06](%155, %45, %46)
  %157 = Relu(%156)
  %158 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%157, %50)
  %159 = InstanceNormalization[epsilon = 9.99999974737875e-06](%158, %51, %52)
  %160 = Add(%154, %159)
  %161 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%160, %56)
  %162 = InstanceNormalization[epsilon = 9.99999974737875e-06](%161, %57, %58)
  %163 = Relu(%162)
  %164 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%163, %62)
  %165 = InstanceNormalization[epsilon = 9.99999974737875e-06](%164, %63, %64)
  %166 = Add(%160, %165)
  %167 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%166, %68)
  %168 = InstanceNormalization[epsilon = 9.99999974737875e-06](%167, %69, %70)
  %169 = Relu(%168)
  %170 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%169, %74)
  %171 = InstanceNormalization[epsilon = 9.99999974737875e-06](%170, %75, %76)
  %172 = Add(%166, %171)
  %173 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%172, %80)
  %174 = InstanceNormalization[epsilon = 9.99999974737875e-06](%173, %81, %82)
  %175 = Relu(%174)
  %176 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%175, %86)
  %177 = InstanceNormalization[epsilon = 9.99999974737875e-06](%176, %87, %88)
  %178 = Add(%172, %177)
  %179 = ConvTranspose[dilations = [1, 1], group = 1, kernel_shape = [4, 4], pads = [1, 1, 1, 1], strides = [2, 2]](%178, %92)
  %180 = InstanceNormalization[epsilon = 9.99999974737875e-06](%179, %93, %94)
  %181 = Relu(%180)
  %182 = ConvTranspose[dilations = [1, 1], group = 1, kernel_shape = [4, 4], pads = [1, 1, 1, 1], strides = [2, 2]](%181, %98)
  %183 = InstanceNormalization[epsilon = 9.99999974737875e-06](%182, %99, %100)
  %184 = Relu(%183)
  %185 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [1, 1]](%184, %104)
  %186 = Tanh(%185)
  return %186
}
```

**Comment by aseemw** [comment]
That is true, since CoreML does not support "Gather" and "Tile" ops the converter is unable to handle them. The suggested workaround is to use custom layers in CoreML. There are some examples [here](https://github.com/onnx/onnx-coreml/blob/dc58afc4fce51d3376f434b20498a9abcf20edf9/tests/custom_layers_test.py#L75) and a nice blog post about the topic [here](http://machinethink.net/blog/coreml-custom-layers/).

**Comment by UdonDa** [comment]
Thank you very much. I will do it like this test.

**Comment by btomtom5** [comment]
The newest version of onnx-coreml now will remove the Gather operation from the graph if the inputs are constant thanks to @aseemw !!  Install from source https://github.com/onnx/onnx-coreml

**Comment by glenn-jocher** [comment]
@btomtom5 I get the same error with Shape and Gather in **PyTorch 1.0.0 exporting to ONNX 1.3.0**  installed from source:
```
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 208, in <module>
    main()
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 32, in main
    yolov3_model = convert(model_proto, image_input_names=['0'], preprocessing_args={'image_scale': 1. / 255})
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 455, in convert
    _check_unsupported_ops(graph.nodes)
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 143, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported ONNX ops of type: Shape,Gather
```

**Comment by pietz** [comment]
@btomtom5 I'm also still getting this error with onnx-coreml 0.3.0

**Comment by Russzheng** [comment]
> @btomtom5 I get the same error with Shape and Gather in **PyTorch 1.0.0 exporting to ONNX 1.3.0** installed from source:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 208, in <module>
>     main()
>   File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 32, in main
>     yolov3_model = convert(model_proto, image_input_names=['0'], preprocessing_args={'image_scale': 1. / 255})
>   File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 455, in convert
>     _check_unsupported_ops(graph.nodes)
>   File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 143, in _check_unsupported_ops
>     ','.join(unsupported_op_types)))
> NotImplementedError: Unsupported ONNX ops of type: Shape,Gather
> ```

Hi same issue here, I am wondering have you resolved it? Thank you so much.

**Comment by Russzheng** [comment]
I encountered very similar issues with Gather and Shape layers. I solved the problem by casting tensor shapes to ints
`int(x.shape[0])`

**Comment by glenn-jocher** [comment]
@Russzheng this gives me warnings on export from pytorch:

```python
/Users/glennjocher/PycharmProjects/test/models.py:122: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bs = int(p.shape[0])  # batch size
```

**Comment by Russzheng** [comment]
> @Russzheng this gives me warnings on export from pytorch:
> 
> ```python
> models.py:122: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   bs = int(p.shape[0])  # batch size
> ```

Hi, if you are explicitly using the tensor shape, then the type casting would make torch.jit unable to track it, so conversion would be wrong. But if you are simply using it as a parameter when creating a layer or etc., it should be totally fine. It will throw warnings, but conversion should be good.

**Comment by ayushoriginal** [comment]
> The newest version of onnx-coreml now will remove the Gather operation from the graph if the inputs are constant thanks to @aseemw !! Install from source https://github.com/onnx/onnx-coreml

I'm still getting NotImplementedError even after installing from source

**Comment by Vampire-Vx** [comment]
Is there any solution yet? Still get the gather and group unsupported error..

**Comment by ayushoriginal** [comment]
Myunderstanding is that most of the limitations came from the layers available in the CoreML NN specification and not from the converter. However, since CoreML 3 beta has just been released during WWDC, and it has many more ops like ONNX, the converter should be able to make use of that. In the next couple of months, the Apple team might considerably update the ONNX converter with the new layers, so the experience of converting NLP models should become much smoother.

**Comment by aseemw** [comment]
Yes, updating of the onnx converter for the new CoreML spec is in the works and updates would be pushed over the next few weeks.

**Comment by bhushan23** [comment]
@MarcSteven could you please pass `minimum_ios_deployment_target=13` to convert method and try?`Shape, Gather` ops are added in CoreML 3 and are supported for iOS 13.

**Comment by MarcSteven** [comment]
> @MarcSteven could you please pass `minimum_ios_deployment_target=13` to convert method and try?`Shape, Gather` ops are added in CoreML 3 and are supported for iOS 13.

But I want to make it support iOS12. How to make it available ?

**Comment by ZackPashkin** [comment]
Solution for **NotImplementedError: Unsupported ONNX ops of type: Shape,Gather** if you use mobilenet v2
import model code from here 
https://github.com/pytorch/vision/blob/master/torchvision/models/mobilenet.py#L180
change 
```
    def _forward_impl(self, x: Tensor) -> Tensor:
        # This exists since TorchScript doesn't support inheritance, so the superclass method
        # (this one) needs to have a name other than `forward` that can be accessed in a subclass
        x = self.features(x)
        # Cannot use "squeeze" as batch-size can be 1 => must use reshape with x.shape[0]
        x = nn.functional.adaptive_avg_pool2d(x, (1, 1)).reshape(x.shape[0], -1)
        x = self.classifier(x)
        return x
```
to 
```
    def _forward_impl(self, x: Tensor) -> Tensor:
        # This exists since TorchScript doesn't support inheritance, so the superclass method
        # (this one) needs to have a name other than `forward` that can be accessed in a subclass
        x = self.features(x)
        # Cannot use "squeeze" as batch-size can be 1 => must use reshape with x.shape[0]
        #convert shape to int
        x = nn.functional.adaptive_avg_pool2d(x, (1, 1)).reshape(int(x.shape[0]), -1)
        x = self.classifier(x)
        return x

```
works with
pip install onnx_coreml==1.2
pip install coremltools==3.2

**Comment by MarcSteven** [comment]
Ok
