### ISSUE TITLE
NotImplementedError: Unsupported ONNX ops of type: Constant

### ISSUE THREAD

**Issue by glenn-jocher** [onnx/onnx-coreml#368]
I'm trying to export the following yolov3-tiny.onnx model to CoreML which I originally exported from PyTorch 1.0 correctly. The pytorch model originates from https://github.com/ultralytics/yolov3, and operates correctly with no issues. There are no PyTorch 'Constant' modules, so I don't understand the origin of the error. Please help.
https://storage.googleapis.com/ultralytics/yolov3-tiny.onnx (35 MB)

```bash
Traceback (most recent call last):
  File "/Users/glennjocher/onnx-coreml/onnx_to_coreml.py", line 24, in <module>
    main()
  File "/Users/glennjocher/onnx-coreml/onnx_to_coreml.py", line 19, in main
    coreml_model = convert(model_proto, image_input_names=['0'], image_output_names=['156'])
  File "/Users/glennjocher/onnx-coreml/onnx_coreml/converter.py", line 455, in convert
    _check_unsupported_ops(graph.nodes)
  File "/Users/glennjocher/onnx-coreml/onnx_coreml/converter.py", line 143, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported ONNX ops of type: Constant
```

**Comment by glenn-jocher** [comment]
I've solved this. Strangely enough it appears the problem was caused by pre-populating a torch tensor (i.e. with zeros) and then redefining its values. I changed my approach to use `torch.stack` and `torch.cat` to create the tensor instead, and now the model appears viewable with the Netron viewer.
