### ISSUE TITLE
TypeError: Error while converting op of type: Concat. Error message: unable to translate constant array shape to CoreML shape

### ISSUE THREAD

**Issue by glenn-jocher** [onnx/onnx-coreml#370]
I am receiving the following error message when converting Pytorch 1.0 -> ONNX model to CoreML. It seems to be due to torch.cat() operations. I am using Python 2.7. The ONNX model is available here:

https://storage.googleapis.com/ultralytics/model_concat_error.onnx (35 MB)

```python
34/40: Converting Node Type LeakyRelu
35/40: Converting Node Type Conv
36/40: Converting Node Type Concat
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/onnx-coreml/onnx_to_coreml.py", line 24, in <module>
    main()
  File "/Users/glennjocher/PycharmProjects/onnx-coreml/onnx_to_coreml.py", line 19, in main
    coreml_model = convert(model_proto, image_input_names=['0'], image_output_names=['156'])
  File "/Users/glennjocher/PycharmProjects/onnx-coreml/onnx_coreml/converter.py", line 463, in convert
    _add_const_inputs_if_required(builder, node, graph, err)
  File "/Users/glennjocher/PycharmProjects/onnx-coreml/onnx_coreml/_operators.py", line 1823, in _add_const_inputs_if_required
    _convert_const(builder, node, graph, err)
  File "/Users/glennjocher/PycharmProjects/onnx-coreml/onnx_coreml/_operators.py", line 1718, in _convert_const
    return err.unsupported_op_configuration(builder, node, graph, "unable to translate constant array shape to CoreML shape")
  File "/Users/glennjocher/PycharmProjects/onnx-coreml/onnx_coreml/_error_utils.py", line 56, in unsupported_op_configuration
    "Error while converting op of type: {}. Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: Concat. 
Error message: unable to translate constant array shape to CoreML shape
```

**Comment by dianxin556** [comment]
I meet the same problem while converting op of type: Add .For this op, it has 2 inputs, one is in the inputTensor, and its shape is [1,3,1,1], another is in onnx_coreml_shape_mapping, its value is [1,2,3,4].But in _convert_const func, it lacks of len(shape)==4: since the inpute tensor is a constant with shape [1,3,1,1].

**Comment by xfarxod** [comment]
Did you  resolve this issue ?

**Comment by bhushan23** [comment]
@dianxin556 could you please give a try to https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3 latest beta?
Feel free to re-open if you still face this issue
