### ISSUE TITLE
issue when converting Keras model

### ISSUE THREAD

**Issue by sariagoudarzvand** [onnx/onnx-coreml#392]
I am using a OCR code written in keras and I would like to convert it to CoreMl,
It raises this error 
```
/home/sgnbx/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/onnx/__init__.py:94: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  decoded = cast(Optional[int], proto.ParseFromString(s))
Traceback (most recent call last):
  File "/home/sgnbx/Downloads/projects/CRNN-with-STN-master/coreml1.py", line 3, in <module>
    mlmodel = convert('weightswithoutstnlrchanged.best.hdf5')
  File "/home/sgnbx/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/onnx_coreml/converter.py", line 340, in convert
    onnx_model = onnx.load(model)
  File "/home/sgnbx/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/onnx/__init__.py", line 114, in load_model
    model = load_model_from_string(s, format=format)
  File "/home/sgnbx/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/onnx/__init__.py", line 151, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/home/sgnbx/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/onnx/__init__.py", line 98, in _deserialize
    decoded, len(s)))
google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 11 out of 62977944

```
any idea how to resolve it?

Thanks

**Comment by nanicpc** [comment]
I have the same problem with the pytorch3.6 environment

```
~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnx/__init__.py in load_model(f, format, load_external_data)
    112     '''
    113     s = _load_bytes(f)
--> 114     model = load_model_from_string(s, format=format)
    115 
    116     if load_external_data:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnx/__init__.py in load_model_from_string(s, format)
    149     Loaded in-memory ModelProto
    150     '''
--> 151     return _deserialize(s, ModelProto())
    152 
    153 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnx/__init__.py in _deserialize(s, proto)
     96         raise google.protobuf.message.DecodeError(
     97             "Protobuf decoding consumed too few bytes: {} out of {}".format(
---> 98                 decoded, len(s)))
     99     return proto
    100 

DecodeError: Protobuf decoding consumed too few bytes: 1 out of 244482357
```

**Comment by bhushan23** [comment]
not a onnx-coreml converter issue
and mostly handled by onnx in it's latest version
