### ISSUE TITLE
Problem converting ONNX to CoreML for model with multiple outputs

### ISSUE THREAD

**Issue by raibosome** [onnx/onnx-coreml#404]
Hi. I am trying to convert a MobileNet-SSD model from PyTorch to ONNX to CoreML. The model returns a tuple of `(bounding_boxes, confidence_values)`. As I ran the following:

```python
from torch.autograd import Variable
import torch.onnx
from vision.ssd.mobilenetv1_ssd import create_mobilenetv1_ssd
import onnx
import onnx_coreml

MODEL_NAME = "githubmodel"
PATH_PTH = f"models/{MODEL_NAME}.pth"
PATH_ONNX = f"models/{MODEL_NAME}.onnx"
PATH_MLMODEL = f"models/{MODEL_NAME}.mlmodel"

# Load PyTorch model
model_pth = create_mobilenetv1_ssd(21, is_test=True)
model_pth.load(PATH_PTH)
model_pth.eval()

# Convert PyTorch to ONNX
dummy_input = Variable(torch.randn(1, 3, 300, 300))
torch.onnx.export(model_pth, dummy_input, PATH_ONNX, 
    input_names = ['image'], 
    output_names= ['coordinates','confidence'])

# Inspect ONNX model
model_onnx = onnx.load(PATH_ONNX)
onnx.checker.check_model(model_onnx)

# Convert ONNX to CoreMLModel
model_onnx = onnx.load(PATH_ONNX)
cml = onnx_coreml.convert(model_onnx)
```

I got the following error:

```
1/154: Converting Node Type Conv
2/154: Converting Node Type BatchNormalization
3/154: Converting Node Type Relu
...
134/154: Converting Node Type Concat
135/154: Converting Node Type Concat
136/154: Converting Node Type Softmax
Traceback (most recent call last):
  File "converteur.py", line 29, in <module>
    cml = onnx_coreml.convert(model_onnx)
  File "/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_coreml/converter.py", line 468, in convert
    _convert_node(builder, node, graph, err)
  File "/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1908, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1081, in _convert_softmax
    return err.unsupported_op_configuration(builder, node, graph, "Unsupported axis {} for softmax".format(axis, ))
  File "/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 56, in unsupported_op_configuration
    "Error while converting op of type: {}. 
        Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: Softmax. 
        Error message: Unsupported axis 2 for softmax
```

I understand that this has something to do with having the tuple as an output of the model (because I was able to successfully do it by making the model only return `bounding_boxes`). This is part of the the `forward()` method in the model:

```python
def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    confidences = []
    locations = []
    start_layer_index = 0
    header_index = 0
     ...
    
    if self.is_test:
        confidences = F.softmax(confidences, dim=2)
        boxes = box_utils.convert_locations_to_boxes(
            locations, self.priors, self.config.center_variance, self.config.size_variance
        )
        boxes = box_utils.center_form_to_corner_form(boxes)
        return confidences, boxes
    else:
        return confidences, locations
```

Similar issues [#5222](https://github.com/pytorch/pytorch/issues/5222#issue-296873437) and [#203](https://github.com/onnx/onnx-tensorflow/issues/203#issue-328831673) were submitted but there was no concrete solution. What is the current practise for converting ONNX **models with multiple outputs** to CoreML?

Thanks!

**Comment by bhushan23** [comment]
@raibosome currently, converter requires softmax on axis 1 - here https://github.com/onnx/onnx-coreml/blob/cd4e491a61daeb9f1d56d3e277ed3d06c40bd7ad/onnx_coreml/_operators.py#L1099

Issue looks like with `confidences = F.softmax(confidences, dim=2)`

But as per your experiments, it works fine if you only return one value, this is weird. Could you please give a try and re-run the experiment?

**Comment by bhushan23** [comment]
@raibosome with latest beta https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3 you can apply softmax on any axis. 
Could you please give it a try?

**Comment by bhushan23** [comment]
feel free to re-open if you still face this issue
