### ISSUE TITLE
Problems Installing

### ISSUE THREAD

**Issue by leonardoaraujosantos** [onnx/onnx-coreml#539]
## 🐞Describe the bug
Hi guys, I'm having Issues with pip install, since last commits

## Trace
If applicable, please paste the error trace.

## To Reproduce

```bash
pip install --upgrade onnx-coreml
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Collecting onnx-coreml
  Using cached https://files.pythonhosted.org/packages/0a/75/8188cc21fdd4d3a4dfaa29df276db1989dc3c5ce9df4a7e0c5ee3687f6da/onnx-coreml-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jm/_7sfbzrd2lvcs9yckwy2rzw80000gn/T/pip-install-MTII2g/onnx-coreml/setup.py", line 4, in <module>
        from onnx_coreml import __version__
      File "onnx_coreml/__init__.py", line 6, in <module>
        from .converter import convert
      File "onnx_coreml/converter.py", line 18, in <module>
        from coremltools import _MINIMUM_NDARRAY_SPEC_VERSION as IOS_13_SPEC_VERSION # iOS 13.0
    ImportError: cannot import name _MINIMUM_NDARRAY_SPEC_VERSION
```

## System environment (please complete the following information):
 - coremltools version  (e.g., 3.0b5):3.1
 - onnx-coreml version (e.g. 1.0b2):1.2
 - OS (e.g., MacOS, Linux):MacOS, Linux
 - How you install python (anaconda, virtualenv, system):pip
 - python version (e.g. 3.7):3.7
 - any other relevant information:

**Comment by leonardoaraujosantos** [comment]
Sorry guys the issue is not installing (and by mistake I was calling pip from python 2.7)
