### ISSUE TITLE
Onnx to mlmodel conversion fails to generate .mlmodel file

### ISSUE THREAD

**Issue by malemo** [onnx/onnx-coreml#564]
I'm trying to convert Pytorch model to MLModel with Onnx.

My code:
```import torch.onnx
import torch
from onnx_coreml import convert
import coremltools

net = BiSeNet(19)
net.cuda()
net.load_state_dict(torch.load('model.pth'))
#net.eval()

dummy = torch.rand(1,3,512,512).cuda()


torch.onnx.export(net, dummy, "Model.onnx", input_names=["image"], output_names=["output"], opset_version=11)

finalModel = convert(model='Model.onnx', minimum_ios_deployment_target='12')
finalModel.save('ModelML.mlmodel')
```
After the code runs Model.onnx is generated, however, .mlmodel file is not generated. There're no errors in the console.

What could be the issue?

**Comment by bhushan23** [comment]
can you try
`print(finalModel)`
before saving the model?  This will help us understand that we indeed have valid mlmodel being converted

**Comment by malemo** [comment]
@bhushan23 I did try print, no output
 
I also tried this
```
onnx_model = onnx.load("Model.onnx")
onnx.checker.check_model(onnx_model)
onnx.helper.printable_graph(onnx_model.graph)
```
Again no output in the console.

I'm running this in Google Collab

**Comment by bhushan23** [comment]
@malemo can you share onnx model?

**Comment by malemo** [comment]
Here is the [Onnx Model](https://drive.google.com/file/d/1thEITb-MlbbCtbzoU-yEJkugxijXn70R/view)
This is original [Pytorch model](https://github.com/zllrunning/face-parsing.PyTorch) I'm trying to convert

**Comment by bhushan23** [comment]
@malemo Please reinstall ONNX-CoreML and try
I see following with latest onnx-coreml beta

```
>>> mlmodel = convert(model='./Model.onnx', minimum_ios_deployment_target='12')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhushansonawane/anaconda3/envs/devenv/lib/python3.7/site-packages/onnx_coreml/converter.py", line 500, in convert
    graph = _prepare_onnx_graph(onnx_model.graph, transformers, onnx_model.ir_version)
  File "/Users/bhushansonawane/anaconda3/envs/devenv/lib/python3.7/site-packages/onnx_coreml/converter.py", line 370, in _prepare_onnx_graph
    graph_ = Graph.from_onnx(graph, onnx_ir_version)
  File "/Users/bhushansonawane/anaconda3/envs/devenv/lib/python3.7/site-packages/onnx_coreml/_graph.py", line 234, in from_onnx
    node_ = Node.from_onnx(node)
  File "/Users/bhushansonawane/anaconda3/envs/devenv/lib/python3.7/site-packages/onnx_coreml/_graph.py", line 115, in from_onnx
    attrs = Attributes.from_onnx(node.attribute)
  File "/Users/bhushansonawane/anaconda3/envs/devenv/lib/python3.7/site-packages/onnx_coreml/_graph.py", line 72, in from_onnx
    d[arg.name] = _convertAttributeProto(arg)
  File "/Users/bhushansonawane/anaconda3/envs/devenv/lib/python3.7/site-packages/onnx_coreml/_graph.py", line 48, in _convertAttributeProto
    raise ValueError("Unsupported ONNX attribute: {}".format(onnx_arg))
ValueError: Unsupported ONNX attribute: name: "strides"
```

Why does it fails?
ONNX model is of opset version 11 (ai.onnx v11)
I would recommend converting to opset version 9 or 10. Support for 11 is not yet added in onnx-coreml.
https://pytorch.org/docs/stable/onnx.html#torch.onnx.export
