### ISSUE TITLE
Unsupported axis 2 for softmax

### ISSUE THREAD

**Issue by iiSeymour** [onnx/onnx-coreml#571]
## 🐞Describe the bug

Converting a model that using `log_softmax` with `dim=2` results in an `TypeError` being thrown during model conversion.

## Trace

```bash
$ convert-onnx-to-coreml  example.onnx -o example.mlmodel
1/3: Converting Node Type Conv
2/3: Converting Node Type Transpose
3/3: Converting Node Type LogSoftmax
Traceback (most recent call last):
  File ".../venv3/bin/convert-onnx-to-coreml", line 8, in <module>
    sys.exit(onnx_to_coreml())
  File ".../venv3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".../venv3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".../venv3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../venv3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".../venv3/lib/python3.7/site-packages/onnx_coreml/bin/convert.py", line 25, in onnx_to_coreml
    coreml_model = convert(onnx_model_proto)
  File ".../venv3/lib/python3.7/site-packages/onnx_coreml/converter.py", line 630, in convert
    _convert_node(builder, node, graph, err)
  File ".../venv3/lib/python3.7/site-packages/onnx_coreml/_operators.py", line 1985, in _convert_node
    return converter_fn(builder, node, graph, err)
  File ".../venv3/lib/python3.7/site-packages/onnx_coreml/_operators.py", line 1117, in _convert_softmax
    return err.unsupported_op_configuration(builder, node, graph, "Unsupported axis {} for softmax".format(axis, ))
  File ".../venv3/lib/python3.7/site-packages/onnx_coreml/_error_utils.py", line 60, in unsupported_op_configuration
    self.rerun_suggestion)
TypeError: Error while converting op of type: LogSoftmax. Error message: Unsupported axis 2 for softmax 
 Please try converting with higher minimum_ios_deployment_target.
You can also provide custom function/layer to convert the model.
```

## To Reproduce

```python
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.layers = nn.Sequential(nn.Conv1d(32, 5, kernel_size=1))
    def forward(self, x):
        x = self.layers(x)
        return nn.functional.log_softmax(x.transpose(1, 2), dim=2)

x = torch.ones((1, 32, 1000))
model = Model()
torch.onnx.export(model, x, 'example.onnx')
```
## System environment (please complete the following information):

macOS Catalina 10.15.4
python 3.7
torch==1.4.0
coremltools==3.3
onnx-coreml==1.3

**Comment by iiSeymour** [comment]
This only seems a problem with the `convert-onnx-to-coreml` command line tool - not a problem when targeting CoreML 3 specifically.

```
from onnx_coreml import convert
mlmodel = convert(model='./example.onnx', minimum_ios_deployment_target='13')
mlmodel.save('example.mlmodel')
```

**Comment by dzyjjpy** [comment]
> This only seems a problem with the `convert-onnx-to-coreml` command line tool - not a problem when targeting CoreML 3 specifically.
> 
> ```
> from onnx_coreml import convert
> mlmodel = convert(model='./example.onnx', minimum_ios_deployment_target='13')
> mlmodel.save('example.mlmodel')
> ```

have you try to solve the issue when "mlmodel = convert(model='./example.onnx', minimum_ios_deployment_target='12')". Afterall, not all the phone run on '13' platform.
