### ISSUE TITLE
ModuleNotFoundError: No module named 'coremltools.converters.nnssa'

### ISSUE THREAD

**Issue by eric573** [onnx/onnx-coreml#585]
## ❓🐛 Question 
Hello! I am having issue importing convert from onnx_coreml. 

## Trace
```
Traceback (most recent call last):
  File "onnx_to_coreml.py", line 3, in <module>
    from onnx_coreml import convert
  File "/Users/name/miniconda3/envs/NST/lib/python3.8/site-packages/onnx_coreml/__init__.py", line 6, in <module>
    from .converter import convert
  File "/Users/name/miniconda3/envs/NST/lib/python3.8/site-packages/onnx_coreml/converter.py", line 35, in <module>
    from coremltools.converters.nnssa.coreml.graph_pass.mlmodel_passes import remove_disconnected_layers, transform_conv_crop
ModuleNotFoundError: No module named 'coremltools.converters.nnssa'

```
## To reproduce
Run this line in python
`from onnx_coreml import convert`

## System Information
- If applicable
Pip Package
coremltools         4.0
onnx-coreml       1.3
onnx                    1.8.0
OS                        Mac OS Big Sur
Python                 3.8.5

**Comment by eric573** [comment]
Ah I just realized the latest version of onnx-coreml recommend converting directly from Pytorch to CoreML. Case Closed!
